# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FMYWeath' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'UIView+Positioning', '~> 1.1'
#    pod 'SwiftyJSON'
#    pod 'Alamofire'

  # Pods for FMYWeath

end
