# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target 'FMYWeath' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'UIView+Positioning', '~> 1.1'
#    pod 'SwiftyJSON'
#    pod 'Alamofire'

   pod 'MJRefresh', '~> 3.1.12'
   pod 'SDWebImage', '~> 4.0.0-beta2'

   pod 'HandyJSON', '~> 5.0.0'
   pod 'SWXMLHash', '~> 4.7.0'
   pod 'Alamofire'
   pod 'SnapKit', '~> 5.0.0'
  # Pods for FMYWeath

end
